---
- hosts: all
  tasks:
  - name: Upgrade all packages
    become: true
    yum: name=* state=latest
    
  - name: Install tools
    become: true
    yum: name={{item}} state=present update_cache=yes
    with_items:
      - ntp
      - screen
      - nginx
      - mysql-server
      - php-fpm
      - php-mysql
#     - php7.0-curl

  - name: Copy .screenrc to skel directory
    become: true
    copy: src=files/.screenrc dest=/etc/skel mode=0644